2021-01-07 00:03:47.007 [warning] <0.353.0> ** Undefined handle_info in rabbitmq
** Unhandled message: {'basic.consume_ok',<<"amq.ctag-VK-mVVX5Y5nVD6IHxCfAHQ">>}
2021-01-07 00:08:29.396 [warning] <0.353.0> ** Undefined handle_info in rabbitmq
** Unhandled message: {'basic.consume_ok',<<"amq.ctag--U8mKrs4-YupzwX5WWLg2g">>}
2021-01-07 00:09:58.465 [warning] <0.353.0> ** Undefined handle_info in rabbitmq
** Unhandled message: {'basic.consume_ok',<<"amq.ctag-Bb0QfFhVZPEjwhySXykESg">>}
2021-01-07 00:10:37.820 [warning] <0.353.0> ** Undefined handle_info in rabbitmq
** Unhandled message: {'basic.consume_ok',<<"amq.ctag-IfEbWiV05H7QuxSnl5drxg">>}
2021-01-07 00:18:25.492 [error] <0.337.0>@rabbitmq:start_consuming_handler:27 gen_server consumer_server terminated with reason: bad argument in call to erlang:spawn(init_consuming_handler, [<0.351.0>,"gholi"]) line 2865 in rabbitmq:start_consuming_handler/2 line 27
2021-01-07 00:18:25.492 [error] <0.337.0>@rabbitmq:start_consuming_handler:27 CRASH REPORT Process consumer_server with 0 neighbours crashed with reason: bad argument in call to erlang:spawn(init_consuming_handler, [<0.351.0>,"gholi"]) line 2865 in rabbitmq:start_consuming_handler/2 line 27
2021-01-07 00:22:39.351 [error] emulator Error in process <0.423.0> with exit value:
{badarg,[{erlang,spawn,[loop_consuming,[<0.421.0>]],[{file,"erlang.erl"},{line,2865}]},{rabbitmq,init_consuming_handler,2,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/src/rabbitmq.erl"},{line,40}]}]}
2021-01-07 00:34:46.565 [error] <0.337.0>@rabbitmq:consume:59 gen_server consumer_server terminated with reason: no function clause matching rabbitmq:consume({[<0.340.0>],[]}, "gholi") line 59
2021-01-07 00:34:46.565 [error] <0.337.0>@rabbitmq:consume:59 CRASH REPORT Process consumer_server with 0 neighbours crashed with reason: no function clause matching rabbitmq:consume({[<0.340.0>],[]}, "gholi") line 59
2021-01-07 11:16:17.758 [error] <0.349.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14546 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-01-07 11:16:17.758 [error] <0.349.0> Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14546 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-07 11:16:17.758 [error] emulator Error in process <0.352.0> with exit value:
{badarg,[{erlang,size,[undefined],[]},{rabbit_framing_amqp_0_9_1,shortstr_size,1,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/_build/default/lib/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl"},{line,178}]},{rabbit_framing_amqp_0_9_1,encode_method_fields,1,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/_build/default/lib/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl"},{line,1114}]},{rabbit_binary_generator,build_simple_method_frame,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/_build/default/lib/rabbit_common/src/rabbit_binary_generator.erl"},{line,50}]},{rabbit_writer,internal_send_command_async,2,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/_build/default/lib/rabbit_common/src/rabbit_writer.erl"},{line,353}]},{rabbit_writer,handle_message,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/_build/default/lib/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/_build/default/lib/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/_build/default/lib/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-07 11:18:33.413 [error] <0.352.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.352.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-01-07 11:18:33.414 [error] <0.349.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14585 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-01-07 11:18:33.414 [error] <0.349.0> Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14585 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-07 11:20:20.947 [error] <0.352.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.352.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-01-07 11:20:20.947 [error] <0.349.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14600 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-01-07 11:20:20.948 [error] <0.349.0> Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14600 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-07 11:37:06.888 [error] <0.352.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.352.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-01-07 11:37:06.888 [error] <0.349.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14822 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-01-07 11:37:06.888 [error] <0.349.0> Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14822 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-07 11:37:57.696 [error] <0.352.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.352.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-01-07 11:37:57.696 [error] <0.349.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14839 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason bad argument in call to erlang:size(undefined) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-01-07 11:37:57.696 [error] <0.349.0> Supervisor {<0.349.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.351.0>, {<<"client 127.0.0.1:14839 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.352.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-07 11:47:22.026 [error] <0.337.0>@lists:delete:376 gen_server consumer_server terminated with reason: no function clause matching lists:delete([<0.353.0>], <0.353.0>) line 376
2021-01-07 11:47:22.026 [error] <0.337.0>@lists:delete:376 CRASH REPORT Process consumer_server with 0 neighbours crashed with reason: no function clause matching lists:delete([<0.353.0>], <0.353.0>) line 376
2021-01-07 14:46:06.281 [error] <0.337.0>@rabbitmq:handle_call:66 gen_server rabbitmq_server terminated with reason: no function clause matching rabbitmq:handle_call({start_consumer,"gholi"}, {<0.266.0>,#Ref<0.1448953890.1718353921.135064>}, {[<0.340.0>],[],[]}) line 66
2021-01-07 14:46:06.281 [error] <0.337.0>@rabbitmq:handle_call:66 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no function clause matching rabbitmq:handle_call({start_consumer,"gholi"}, {<0.266.0>,#Ref<0.1448953890.1718353921.135064>}, {[<0.340.0>],[],[]}) line 66
2021-01-07 14:47:40.283 [error] <0.337.0>@rabbitmq:consume:125 gen_server rabbitmq_server terminated with reason: bad argument in call to erlang:list_to_atom(<0.353.0>) in rabbitmq:consume/2 line 125
2021-01-07 14:47:40.283 [error] <0.337.0>@rabbitmq:consume:125 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: bad argument in call to erlang:list_to_atom(<0.353.0>) in rabbitmq:consume/2 line 125
2021-01-07 14:49:25.155 [error] <0.337.0>@rabbitmq:consume:125 gen_server rabbitmq_server terminated with reason: bad argument in call to erlang:register(<0.353.0>, <0.351.0>) in rabbitmq:consume/2 line 125
2021-01-07 14:49:25.155 [error] <0.337.0>@rabbitmq:consume:125 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: bad argument in call to erlang:register(<0.353.0>, <0.351.0>) in rabbitmq:consume/2 line 125
2021-01-07 17:16:24.984 [error] <0.337.0>@rabbitmq:create_queue:207 gen_server rabbitmq_server terminated with reason: bad argument in call to erlang:list_to_binary(<<"gholi">>) in rabbitmq:create_queue/2 line 207
2021-01-07 17:16:24.984 [error] <0.337.0>@rabbitmq:create_queue:207 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: bad argument in call to erlang:list_to_binary(<<"gholi">>) in rabbitmq:create_queue/2 line 207
2021-01-07 17:21:51.542 [error] <0.337.0>@rabbitmq:handle_call:69 gen_server rabbitmq_server terminated with reason: no match of right hand value false in rabbitmq:handle_call/3 line 69
2021-01-07 17:21:51.542 [error] <0.337.0>@rabbitmq:handle_call:69 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no match of right hand value false in rabbitmq:handle_call/3 line 69
2021-01-07 17:38:39.193 [error] <0.337.0>@rabbitmq:handle_call:68 gen_server rabbitmq_server terminated with reason: no match of right hand value {<0.351.0>,"gholi"} in rabbitmq:handle_call/3 line 68
2021-01-07 17:38:39.193 [error] <0.337.0>@rabbitmq:handle_call:68 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no match of right hand value {<0.351.0>,"gholi"} in rabbitmq:handle_call/3 line 68
2021-01-07 17:41:06.369 [error] <0.337.0>@rabbitmq:handle_call:67 gen_server rabbitmq_server terminated with reason: no match of right hand value {<0.351.0>,"gholi"} in rabbitmq:handle_call/3 line 67
2021-01-07 17:41:06.369 [error] <0.337.0>@rabbitmq:handle_call:67 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no match of right hand value {<0.351.0>,"gholi"} in rabbitmq:handle_call/3 line 67
2021-01-07 17:43:16.586 [error] <0.337.0> gen_server rabbitmq_server terminated with reason: {{function_clause,[{gen,do_for_proc,["gholi",#Fun<gen.0.110169649>],[{file,"gen.erl"},{line,311}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,242}]},{rabbitmq,handle_call,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/src/rabbitmq.erl"},{line,72}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{gen_server,call,["gholi",{close,...},...]}} in gen_server:call/3 line 246
2021-01-07 17:43:16.586 [error] <0.337.0> CRASH REPORT Process rabbitmq_server with 0 neighbours exited with reason: {{function_clause,[{gen,do_for_proc,["gholi",#Fun<gen.0.110169649>],[{file,"gen.erl"},{line,311}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,242}]},{rabbitmq,handle_call,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/src/rabbitmq.erl"},{line,72}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{gen_server,call,["gholi",{close,...},...]}} in gen_server:call/3 line 246
2021-01-07 17:45:44.766 [error] <0.337.0> gen_server rabbitmq_server terminated with reason: {{function_clause,[{gen,do_for_proc,["gholi",#Fun<gen.0.110169649>],[{file,"gen.erl"},{line,311}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,242}]},{rabbitmq,handle_call,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/src/rabbitmq.erl"},{line,69}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{gen_server,call,["gholi",{close,...},...]}} in gen_server:call/3 line 246
2021-01-07 17:45:44.766 [error] <0.337.0> CRASH REPORT Process rabbitmq_server with 0 neighbours exited with reason: {{function_clause,[{gen,do_for_proc,["gholi",#Fun<gen.0.110169649>],[{file,"gen.erl"},{line,311}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,242}]},{rabbitmq,handle_call,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/src/rabbitmq.erl"},{line,69}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{gen_server,call,["gholi",{close,...},...]}} in gen_server:call/3 line 246
2021-01-07 17:47:37.240 [error] <0.337.0> gen_server rabbitmq_server terminated with reason: {{function_clause,[{gen,do_for_proc,["gholi",#Fun<gen.0.110169649>],[{file,"gen.erl"},{line,311}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,242}]},{rabbitmq,handle_call,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/src/rabbitmq.erl"},{line,69}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{gen_server,call,["gholi",{close,...},...]}} in gen_server:call/3 line 246
2021-01-07 17:47:37.240 [error] <0.337.0> CRASH REPORT Process rabbitmq_server with 0 neighbours exited with reason: {{function_clause,[{gen,do_for_proc,["gholi",#Fun<gen.0.110169649>],[{file,"gen.erl"},{line,311}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,242}]},{rabbitmq,handle_call,3,[{file,"c:/Users/Sina/IdeaProjects/uniSup/erlang_server/src/rabbitmq.erl"},{line,69}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{gen_server,call,["gholi",{close,...},...]}} in gen_server:call/3 line 246
2021-01-07 17:48:59.764 [error] <0.337.0>@rabbitmq:handle_call:70 gen_server rabbitmq_server terminated with reason: bad argument in rabbitmq:handle_call/3 line 70
2021-01-07 17:48:59.764 [error] <0.337.0>@rabbitmq:handle_call:70 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: bad argument in rabbitmq:handle_call/3 line 70
2021-01-07 17:50:51.737 [error] <0.337.0>@lists:delete:376 gen_server rabbitmq_server terminated with reason: no function clause matching lists:delete("gholi", {"gholi","gholi"}) line 376
2021-01-07 17:50:51.737 [error] <0.337.0>@lists:delete:376 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no function clause matching lists:delete("gholi", {"gholi","gholi"}) line 376
2021-01-07 17:53:03.310 [error] <0.337.0>@lists:delete:376 gen_server rabbitmq_server terminated with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {"gholi",<0.351.0>}) line 376
2021-01-07 17:53:03.310 [error] <0.337.0>@lists:delete:376 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {"gholi",<0.351.0>}) line 376
2021-01-07 17:53:42.925 [error] <0.337.0>@lists:delete:376 gen_server rabbitmq_server terminated with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {<0.351.0>,"gholi"}) line 376
2021-01-07 17:53:42.925 [error] <0.337.0>@lists:delete:376 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {<0.351.0>,"gholi"}) line 376
2021-01-07 17:54:45.452 [error] <0.337.0>@lists:delete:376 gen_server rabbitmq_server terminated with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {<0.351.0>,"gholi"}) line 376
2021-01-07 17:54:45.452 [error] <0.337.0>@lists:delete:376 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {<0.351.0>,"gholi"}) line 376
2021-01-07 17:55:32.187 [error] <0.337.0>@lists:delete:376 gen_server rabbitmq_server terminated with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {<0.351.0>,"gholi"}) line 376
2021-01-07 17:55:32.187 [error] <0.337.0>@lists:delete:376 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no function clause matching lists:delete([{<0.351.0>,"gholi"}], {<0.351.0>,"gholi"}) line 376
2021-01-07 18:53:16.522 [error] <0.346.0> gen_server <0.346.0> terminated with reason: {socket_error,timeout}
2021-01-07 18:53:16.522 [error] <0.346.0> CRASH REPORT Process <0.346.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 805
2021-01-07 18:53:16.523 [error] <0.340.0> gen_server <0.340.0> terminated with reason: {socket_error,timeout}
2021-01-07 18:53:16.523 [error] <0.340.0> CRASH REPORT Process <0.340.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 805
2021-01-07 18:53:16.523 [error] <0.339.0> Supervisor {<0.339.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.340.0>, <0.344.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:7586 -> 127.0.0.1:5672">>) at <0.346.0> exit with reason {socket_error,timeout} in context child_terminated
2021-01-07 18:53:16.523 [error] <0.339.0> Supervisor {<0.339.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.340.0>, <0.344.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:7586 -> 127.0.0.1:5672">>) at <0.346.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-07 18:53:16.523 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.340.0> exit with reason {socket_error,timeout} in context child_terminated
2021-01-07 18:53:16.523 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.340.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-07 20:09:15.553 [error] <0.337.0>@rabbitmq:handle_call:67 gen_server rabbitmq_server terminated with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-07 20:09:15.553 [error] <0.337.0>@rabbitmq:handle_call:67 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-07 20:10:44.029 [error] <0.337.0>@rabbitmq:handle_call:67 gen_server rabbitmq_server terminated with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-07 20:10:44.029 [error] <0.337.0>@rabbitmq:handle_call:67 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-07 20:11:44.224 [error] <0.337.0>@rabbitmq:handle_call:69 gen_server rabbitmq_server terminated with reason: bad argument in call to io:format(<0.261.0>, "consumer new status: ~p~n", {[<0.340.0>],[],[]}) in rabbitmq:handle_call/3 line 69
2021-01-07 20:11:44.224 [error] <0.337.0>@rabbitmq:handle_call:69 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: bad argument in call to io:format(<0.261.0>, "consumer new status: ~p~n", {[<0.340.0>],[],[]}) in rabbitmq:handle_call/3 line 69
2021-01-07 20:13:28.522 [error] <0.337.0>@rabbitmq:handle_call:67 gen_server rabbitmq_server terminated with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-07 20:13:28.522 [error] <0.337.0>@rabbitmq:handle_call:67 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-07 20:23:23.930 [error] <0.337.0>@rabbitmq:handle_call:67 gen_server rabbitmq_server terminated with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-07 20:23:23.930 [error] <0.337.0>@rabbitmq:handle_call:67 CRASH REPORT Process rabbitmq_server with 0 neighbours crashed with reason: no match of right hand value false in rabbitmq:handle_call/3 line 67
2021-01-15 15:24:59.843 [error] <0.348.0>@rabbitmq:create_connection:117 CRASH REPORT Process <0.348.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in rabbitmq:create_connection/0 line 117
2021-01-18 10:48:25.402 [error] <0.273.0>@rabbitmq:create_connection:117 CRASH REPORT Process <0.273.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in rabbitmq:create_connection/0 line 117
